on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: scaksacr01.azurecr.io
        username: ${{ secrets.acr_scaksacr01_username }}
        password: ${{ secrets.acr_scaksacr01_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/azure-vote" -f  "azure-vote/Dockerfile" -t scaksacr01.azurecr.io/scaks01:${{ github.sha }}
        docker push scaksacr01.azurecr.io/scaks01:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_scaks01_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep scaks01ad92 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace scaks01ad92`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: scaks01ad92
        container-registry-url: scaksacr01.azurecr.io
        container-registry-username: ${{ secrets.acr_scaksacr01_username }}
        container-registry-password: ${{ secrets.acr_scaksacr01_password }}
        secret-name: scaks01dockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: scaks01ad92
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          scaksacr01.azurecr.io/scaks01:${{ github.sha }}
        imagepullsecrets: |
          scaks01dockerauth